version: '3'

services:
    spark:
        image: docker.io/bitnami/spark:3.3
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        ports:
            - 8080:8080
        networks:
            - spark
    spark-worker-1:
        image: docker.io/bitnami/spark:3.3
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=2G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        ports:
            - 20041:4041
        networks:
            - spark
    minio:
        image: docker.io/bitnami/minio:2022
        environment:
            - MINIO_ROOT_USER=minio-root-user
            - MINIO_ROOT_PASSWORD=minio-root-password
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - minio_data:/data
        networks:
            - spark
    spark-notebook:
        image: dhinojosa/bitnami-spark-notebook:3.3
        ports:
            - 8888:8888
        networks:
            - spark
        volumes:
            - notebook_data:/opt/bitnami/spark/work
volumes:
    minio_data:
    notebook_data:
networks:
  spark: